[tool.poetry]
name = "typeid-python"
version = "0.3.3"
description = "Python implementation of TypeIDs: type-safe, K-sortable, and globally unique identifiers inspired by Stripe IDs"
authors = ["Murad Akhundov <akhundov1murad@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/akhundMurad/typeid-python"
classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Operating System :: OS Independent",
]
keywords = ["typeid", "uuid", "uuid6", "guid"]
packages = [{ include = "typeid" }]


[tool.hatch.build.targets.sdist]
exclude = [
  "/.github",
  "/docs",
  "/examples",
  "/deps",
  "/htmlcov",
  "/tests",
  "mkdocs-plugins.code-workspace",
  "Makefile",
  "CODE_OF_CONDUCT.md",
  ".isort.cfg",
  ".gitignore",
  ".flake8",
  "junit",
  "requirements.txt",
  "mypy.ini",
  "pytest.ini",
  ".flake8",
  "pytest.ini",
]


[tool.poetry.dependencies]
python = ">=3.10,<4"
uuid6 = ">=2024.7.10,<2026.0.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.2"
black = "^23.3.0"
mypy = "^1.3.0"
requests = "^2.31.0"
pyyaml = "^6.0"
ruff = "^0.14.5"


[tool.poetry.extras]
cli = ["click"]

[tool.poetry.scripts]
typeid = "typeid.cli:cli"


[tool.pylint]
disable = ["C0111", "C0116", "C0114", "R0903"]

[tool.ruff]
line-length = 119
target-version = "py310"
src = ["typeid", "tests"]

[tool.ruff.lint]
select = ["E", "F", "W", "B", "I"]
ignore = ["E203", "B028"]

[tool.ruff.lint.isort]
known-first-party = ["typeid"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
